---
title: "Discussion_single year (ELAPSE)"
author: "Youchen"
date: "01/26/2021"
output:
  slidy_presentation: default
  ioslides_presentation: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, fig.width = 6, fig.height = 6, warning=F)
library(dplyr)
library(raster)
library(sf)
library(car)  # for running slr
library(GWmodel)  #gwr
library(ranger) # Random forests
library(caret)  #data partition
library(splitstackshape)   #stratified function in this library is better than createDataPartition in library caret
library(splitTools)
library(APMtools)
library(tidyr)
library(viridis)
library(MASS)
library(tmap)
library(tiff)
library(kableExtra)
```
```{r read data}


```

```{r}
global_vars <- "no2_10MACC"
perfm <- lapply(paste0('data/workingData/', list.files('data/workingData/', 'model_perf_')), 
                function(file_name) read.csv(file_name, header=T) )
perfm <- do.call(rbind, perfm)
perfm <- perfm[!(duplicated(perfm$csv_name)&perfm$model=='slr'), ]
perfm$reg_grdsize <- c(NA, lapply(perfm$csv_name[2:nrow(perfm)], function(f) strsplit(f, '_')[[1]][2]) %>% unlist() %>% as.numeric())
perfm$kernel <- c(NA, lapply(perfm$csv_name[2:nrow(perfm)], function(f) strsplit(f, '_')[[1]][3]) %>% unlist() %>% as.character())
perfm$adaptive <- c(NA, lapply(perfm$csv_name[2:nrow(perfm)], function(f){
   ifelse((length(strsplit(f, '_')[[1]])>4)&(strsplit(f, '_')[[1]][5]=='ad'),
          'adaptive bandwidth', 'fixed bandwidth')
}) %>% unlist())
perfm$global <- c(NA, lapply(perfm$csv_name[2:nrow(perfm)], function(f){
   ifelse(((length(strsplit(f, '_')[[1]])==5)&(strsplit(f, '_')[[1]][5]=='mixed'))|
             ((length(strsplit(f, '_')[[1]])==6)&(strsplit(f, '_')[[1]][6]=='mixed')),
          paste0('global ', global_vars), paste0('local ', global_vars))
}) %>% unlist())
perfm %>% dplyr::filter(kernel=='exponential', adaptive=="adaptive bandwidth") %>% rbind(perfm[1,]) %>% arrange(rsq) %>% kbl(full_width = F)
# perfm %>% dplyr::filter(kernel=='gaussian')%>% rbind(perfm[1,]) %>% arrange(rsq) %>% kbl(full_width = F)


```

# Adaptive bandwidth (exponential)


```{r}
perfm %>% dplyr::filter(kernel=='exponential', adaptive=='adaptive bandwidth') %>% rbind(perfm[1,]) %>% arrange(rsq) %>% kbl(full_width = F)
```


# Gridsize = 1000km (exponential)

```{r}
perfm %>% dplyr::filter(kernel=='exponential', reg_grdsize==1000, adaptive=='adaptive bandwidth') %>% rbind(perfm[1,]) %>% arrange(rsq) %>% kbl(full_width = F)
```


```{r}
show_gwr_coef <- function(i){
   
   grid::grid.raster( tiff::readTIFF(paste0("graph/gwr_coef/", csv_names_slr[i],".tiff")) )
}

```

