---
title: "gwr grid cell size"
author: "Youchen Shen"
date: "3/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("scr/fun_call_lib.R")
source("scr/fun_read_data.R")
regression_grd_cellsize <- c(10, 20, 50, 80, 100, 200, 500, 600, 1000, 1500, 2000)   #km
kernels <- c('exponential')
year_target <- 2010
csv_names <- paste0("testGWR_", regression_grd_cellsize, "_", kernels, "_", year_target, ".tif")

```

## R2 vs grid cell size



```{r}
perfm <- lapply(paste0('data/workingData/', list.files('data/workingData/', 'test_grdsize_')), 
                function(file_name) read.csv(file_name, header=T) )

perfm <- do.call(rbind, perfm)
perfm$reg_grdsize <- c(lapply(perfm$csv_name[1:nrow(perfm)], function(f) strsplit(f, '_')[[1]][2]) %>% unlist() %>% as.numeric())
perfm$kernel <- c(lapply(perfm$csv_name[1:nrow(perfm)], function(f) strsplit(f, '_')[[1]][3]) %>% unlist() %>% as.character())
ggplot(perfm)+
   geom_line(aes(x=reg_grdsize, y=rsq, col=df_type))+
   geom_point(aes(x=reg_grdsize, y=rsq, col=df_type))+
   labs(title=paste0(unique(perfm$year), " (", unique(perfm$kernel), ")"),
        x='grid cell size of regression coefficients (km)',
        y='R squared',
        col='data type')
```

## Parameter surfaces with different grid cell sizes
For 

```{r}
no2_e_target <- subset_df_yrs(no2_e_all, year_target)
data_all <- no2_e_target

#f# stratified by station types, climate zones and/or years
set.seed(seed)
data_all$index <- 1:nrow(data_all)
train_sub <- stratified(data_all, c('type_of_st', 'zoneID'), 0.8)
test_sub <- data_all[-train_sub$index, ]
data_all <- rbind(train_sub, test_sub)
#f# SLR: select predictors
source("scr/fun_call_predictor.R")
#f# SLR: define/preprocess predictors (direction of effect)
source("scr/fun_slr_proc_in_data.R")
train_sub <- proc_in_data(train_sub, neg_pred)
test_sub <- proc_in_data(test_sub, neg_pred)
data_all <- rbind(train_sub, test_sub)
```

```{r}
source("scr/fun_setupt_gwr.R")
# setup <- lapply(regression_grd_cellsize, function(grdcell){
#    setup_gwr(train_sub, eu_bnd, 
#              cellsize = grdcell*1000, local_crs = local_crs)
# })
# sp_train <- setup[[1]]
# grd <- setup[[2]]
# DM <- setup[[3]]
# plot(coordinates(grd), col='red', pch=18)
# plot(grd, add=T, col='dark green')
# plot(eu_bnd[1], pch=16, col='transparent',add=TRUE)
# plot(sp_train, add=T)
```


It took less than a minute to run the smallest regression grid cell size (in this case: 10km)

```{r pressure, echo=FALSE}
slr <- read.csv(paste0("data/workingData/SLR_summary_model_run2_", year_target,".csv"))
eq <- as.formula(paste0('obs~',  paste(slr$variables[-1], collapse = "+")))

source("scr/fun_setupt_gwr.R")

gwr_models <- lapply(csv_names, function(filename) {
   raster_stack <- stack(paste0("data/workingData/gwr_coef/", filename))
   names(raster_stack) <- c("Intercept", slr$variables[-1])
   raster_stack
})
# sapply(gwr_models, function(gwr_m) names(gwr_m))

# for(plot_i in seq_along(names(gwr_models[[1]]))){ #seq_along(names(gwr_model$SDF))
#    
#    var_target <- names(gwr_models[[1]])[plot_i]
#    var_r <- lapply(seq_along(gwr_models), function(gwr_i){
#       rl <- gwr_models[[gwr_i]][[plot_i]]
#       names(rl) <- paste0(names(gwr_models[[1]])[plot_i], "_", regression_grd_cellsize[gwr_i])
#       rl
#    })
#    var_rc <- lapply(var_r, function(r){
#       resample(r, var_r[[1]], method='ngb')
#    })
#    
#    var_rcs <- stack(var_rc)
#    tmap_mode("plot")
#    var_maps <- tm_shape(var_rcs)+
#       tm_raster(palette = viridis(5), style = "cont", title = '')+
#       tm_shape(eu_bnd) +
#       tm_borders(col='black')+
#       tm_layout(legend.title.size = 1, legend.text.size = 0.8, 
#                 legend.text.color = 'black', 
#                 title = var_target,
#                 title.color = 'black')+
#       tm_facets(as.layers = TRUE)
#    tmap_save(var_maps, filename = paste0('graph/gwr_coef/testGWR_', kernels, "_", year_target, "_",  names(gwr_models[[1]])[plot_i],".tiff"), 
#              dpi=100, height=5, width=7, units='in')
#    
#    # # tmap_mode("view")
#    # tm_shape(var_rcs)+
#    #    tm_raster(palette = viridis(5), style = "cont", title = '')+
#    #    tm_shape(eu_bnd) +
#    #    tm_borders(col='black')+
#    #    tm_layout(legend.title.size = 1, legend.text.size = 0.8, 
#    #              legend.text.color = 'black', 
#    #              title = var_target,
#    #              title.color = 'black')
# }
```

```{r}
gwr_models[[6]]
source("scr/fun_setupt_gwr.R")
nngb <- read.table(paste0("data/workingData/GWR_nngb_run2_",
                                  year_target, ".txt"))[,1]

setup1 <- setup_gwr(train_sub, eu_bnd,
             cellsize = regression_grd_cellsize[3]*1000, local_crs = local_crs)
sp_train1 <- setup1[[1]]
grd1 <- setup1[[2]]
DM1 <- setup1[[3]]
grd_mp1 <- raster(grd1) %>% rasterToPolygons() %>% st_as_sf(crs = 3035) %>% st_cast("MULTIPOLYGON")
grd_mp1$layer <- seq_len(ncol(DM1))
grd_p1 <- st_as_sf(grd1)
grd_p1$layer <- seq_len(ncol(DM1))

setup2 <- setup_gwr(train_sub, eu_bnd,
             cellsize = regression_grd_cellsize[6]*1000, local_crs = local_crs)
sp_train2 <- setup2[[1]]
grd2 <- setup2[[2]]
DM2 <- setup2[[3]]
grd_mp2 <- raster(grd2) %>% rasterToPolygons() %>% st_as_sf(crs = 3035) %>% st_cast("MULTIPOLYGON")
grd_mp2$layer <- seq_len(ncol(DM2))
grd_p2 <- st_as_sf(grd2)
grd_p2$layer <- seq_len(ncol(DM2))



# grd50km <- tm_shape(sp_train, projection=crs(eu_bnd)) +
#   tm_dots( "gwr_w1", col = "gwr_w1", size = 0.05,
#      popup.vars = c("gwr_w1","obs"))+
#    tm_shape(grd_p1)+
#    tm_dots(alpha=0.2)+
#    tm_shape(grd_mp1) +
#       tm_borders(col='green')+
#    tm_shape(grd_mp1)+
#    tm_text("layer")
# tmap_save(grd50km, "grd50km.html")

# grd200km <- tm_shape(sp_train, projection=crs(eu_bnd)) +
#   tm_dots( "gwr_w2", col = "gwr_w2", size = 0.05,
#      popup.vars = c("gwr_w2","obs"))+
#    tm_shape(grd_p2)+
#    tm_dots(alpha=0.2)+
#    tm_shape(grd_mp2) +
#       tm_borders(col='green')+
#    tm_shape(grd_mp2)+
#    tm_text("layer")
# tmap_save(grd200km, "grd200km.html")



```

```{r}
var_rcs <- vector(mode='list', length=length(names(gwr_models[[1]])))
for(plot_i in seq_along(names(gwr_models[[1]]))){ #seq_along(names(gwr_model$SDF))
   
   var_target <- names(gwr_models[[1]])[plot_i]
   var_r <- lapply(c(3,6), function(gwr_i){
      rl <- gwr_models[[gwr_i]][[plot_i]]
      names(rl) <- paste0(names(gwr_models[[1]])[plot_i], "_", regression_grd_cellsize[gwr_i])
      rl
   })
   var_rc <- lapply(var_r, function(r){
      resample(r, var_r[[1]], method='ngb')
   })
   var_rcs[[plot_i]] <- stack(var_rc)
}
```

```{r}
tmap_plot= function(grd_i1, grd_i2){
   tmap_mode("view")
   sp_train <- sp_train1
   # gw.weight(DM[,grd_i], nngb, kernels, T) %>% hist  #grd_i is the regression point index.
   # gw.weight(DM[,grd_i], nngb, kernels, T) %>% length  #grd_i is the regression point index.
   sp_train$gwr_w1 <- gw.weight(DM1[,grd_i1], nngb, kernels, T) %>% as.vector()
   sp_train$gwr_w2 <- gw.weight(DM2[,grd_i2], nngb, kernels, T) %>% as.vector()
   # sp_train$gwr_w1cat <- cut(sp_train$gwr_w1, breaks=seq(0, 1, 0.2))
   # sp_train$gwr_w2cat <- cut(sp_train$gwr_w2, breaks=seq(0, 1, 0.2))
   
   grdcomb <- tm_shape(sp_train) +
      tm_dots(c("gwr_w1", "gwr_w2"), size = 0.05,
              popup.vars = c("gwr_w1", "gwr_w2"))+
      tm_facets(nrow = 1, sync = TRUE)+
      # tm_dots( "gwr_w1", col = "gwr_w1", size = 0.05,
      #    popup.vars = c("gwr_w1","obs"))+
      #  tm_facets(c("gwr_w1cat", "gwr_w2cat"), free.coords = FALSE, sync=T)+
      tm_shape(grd_p2[grd_p2$layer==grd_i2,])+
      tm_dots(alpha=0.2)+
      tm_shape(grd_mp2[grd_mp2$layer==grd_i2,]) +
      tm_borders(col='green')+
      tm_shape(grd_mp2[grd_mp2$layer==grd_i2,])+
      tm_text("layer")+
      tm_view(set.view = c(st_coordinates(grd_p2[grd_p2$layer==grd_i2,] %>% st_transform(st_crs(4326))) %>% as.vector(), 6))+
      tm_shape(grd_p1[grd_p1$layer==grd_i1,])+
      tm_dots(alpha=0.2)+
      tm_shape(grd_mp1[grd_mp1$layer==grd_i1,]) +
      tm_borders(col='green')+
      tm_shape(grd_mp1[grd_mp1$layer==grd_i1,])+
      tm_text("layer")+
      # add coef raster surface
      tm_shape(var_rcs[[4]]$MAJRDS_EU_1p_50)+
      tm_raster(palette = viridis(5), style = "cont")
   
   grdmap1 <- tm_shape(sp_train) +
      tm_dots(c("gwr_w1"), size = 0.05,
              popup.vars = c("gwr_w1", "gwr_w2"))+
      tm_facets(nrow = 1, sync = TRUE)+
      # tm_dots( "gwr_w1", col = "gwr_w1", size = 0.05,
      #    popup.vars = c("gwr_w1","obs"))+
      #  tm_facets(c("gwr_w1cat", "gwr_w2cat"), free.coords = FALSE, sync=T)+
      tm_shape(grd_p1[grd_p1$layer==grd_i1,])+
      tm_dots(alpha=0.2)+
      tm_shape(grd_mp1[grd_mp1$layer==grd_i1,]) +
      tm_borders(col='green')+
      tm_shape(grd_mp2[grd_mp2$layer==grd_i2,])+
      tm_borders(col='green', alpha=0.3)+
      tm_shape(grd_mp1[grd_mp1$layer==grd_i1,])+
      tm_text("layer")+
      tm_view(set.view = c(st_coordinates(grd_p1[grd_p1$layer==grd_i1,] %>% st_transform(st_crs(4326))) %>% as.vector(), 6))+
       # add coef raster surface
      tm_shape(var_rcs[[4]]$MAJRDS_EU_1p_50)+
      tm_raster(palette = viridis(5), breaks = seq(0, 0.03, 0.005), style = "cont")+
   
   # tm_shape(var_rcs[[4]])+
   #    tm_raster(palette = viridis(5), style = "cont", title = '')+
   #    tm_shape(eu_bnd) +
   #    tm_borders(col='black')+
   #    tm_layout(legend.title.size = 1, legend.text.size = 0.8,
   #              legend.text.color = 'black',
   #              title = var_target,
   #              title.color = 'black')
   
   grdmap2 <- tm_shape(sp_train) +
      tm_dots(c("gwr_w2"), size = 0.05,
              popup.vars = c("gwr_w1", "gwr_w2"))+
      tm_shape(grd_p2[grd_p2$layer==grd_i2,])+
      tm_dots(alpha=0.2)+
      tm_shape(grd_mp2[grd_mp2$layer==grd_i2,]) +
      tm_borders(col='green')+
      tm_shape(grd_mp2[grd_mp2$layer==grd_i2,])+
      tm_text("layer")+
      tm_view(set.view = c(st_coordinates(grd_p2[grd_p2$layer==grd_i2,] %>% st_transform(st_crs(4326))) %>% as.vector(), 6))+
      tm_shape(grd_mp1[grd_mp1$layer==grd_i1,]) +
      tm_borders(col='green', alpha=0.3)+
      # add coef raster surface
      tm_shape(var_rcs[[4]]$MAJRDS_EU_1p_200)+
      tm_raster(palette = viridis(5), breaks = seq(0, 0.03, 0.005), style = "cont")
   
   tmap_arrange(grdmap1, grdmap2, sync=T, nrow=1)
    
}

```

```{r}
grd_n2=256
grd_n1=st_intersection(grd_mp1, grd_p2[grd_p2$layer==grd_n2,])$layer +1
tmap_plot(grd_n1, grd_n2)
```


```{r}
grd_n2=280
grd_n1=st_intersection(grd_mp1, grd_p2[grd_p2$layer==grd_n2,])$layer+1
tmap_plot(grd_n1, grd_n2)

```


