---
title: "gwr grid cell size"
author: "Youchen Shen"
date: "3/16/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("scr/fun_call_lib.R")
source("scr/fun_read_data.R")
regression_grd_cellsize <- c(10, 20, 50, 80, 100, 200, 500, 600, 1000, 1500, 2000)   #km
kernels <- c('exponential')
year_target <- 2010
csv_names <- paste0("testGWR_", regression_grd_cellsize, "_", kernels, "_", year_target, ".tif")

```

## R2 vs grid cell size
```{r}
prefix <- unique(substr(csv_names, 1, nchar(csv_names)-7))
df_all <- lapply(paste0('data/workingData/NO2_5cv_', prefix, ".csv"), read.csv)
df_all <- lapply(seq_along(df_all), function(df_i) df_all[[df_i]] %>% mutate(grid_cell=strsplit(prefix[df_i], "_")[[1]][2]))
perfmm <- lapply(df_all, function(df_data) df_data %>% group_by(nfold) %>% summarise(rsq=error_matrix(obs, gwr)[7], grd_cell=unique(grid_cell))) 
perfmm <- do.call(rbind, perfmm)
perfm <- lapply(df_all, function(df_data) c(error_matrix(df_data$obs, df_data$gwr), grd_cell=as.numeric(unique(df_data$grid_cell))))
perfm <- do.call(rbind, perfm) %>% as.data.frame() 
perfmm$nfold <- as.factor(perfmm$nfold)
perfmm$grd_cell <- as.numeric(perfmm$grd_cell)
# ggplot(perfmm)+
#    geom_point(aes(x=grd_cell, y=rsq, col=nfold, group=nfold))+
#    geom_line(aes(x=grd_cell, y=rsq, col=nfold, group=nfold))+
#    # facet_grid(df_type~.)+
#    labs(title=paste0(year_target),
#         x='grid cell size of regression coefficients (km)',
#         y='R squared',
#         col='data type')+
#    theme(axis.title = element_text(size = 18),
#           axis.text = element_text(size = 16),
#           legend.title = element_text(size = 16),
#           legend.text = element_text(size = 16))

g1 <- ggplot(perfm %>% filter(grd_cell<500))+
   geom_point(aes(x=grd_cell, y=rsq))+
   geom_line(aes(x=grd_cell, y=rsq))+
   # facet_grid(df_type~.)+
   labs(title=paste0(year_target),
        x='grid cell size of regression coefficients (km)',
        y='R squared',
        col='data type')+
   theme(axis.title = element_text(size = 18),
          axis.text = element_text(size = 16),
          legend.title = element_text(size = 16),
          legend.text = element_text(size = 16))

g2 <- ggplot(perfm)+
   geom_point(aes(x=grd_cell, y=RMSE))+
   geom_line(aes(x=grd_cell, y=RMSE))+
   # facet_grid(df_type~.)+
   labs(title=paste0(year_target),
        x='grid cell size of regression coefficients (km)',
        y='RMSE',
        col='data type')+
   theme(axis.title = element_text(size = 18),
          axis.text = element_text(size = 16),
          legend.title = element_text(size = 16),
          legend.text = element_text(size = 16))

grid.arrange(g1, g2, nrow=1)
```



```{r}
perfm <- lapply(paste0('data/workingData/', list.files('data/workingData/', 'test_grdsize_')), 
                function(file_name) read.csv(file_name, header=T) )
perfm <- do.call(rbind, perfm)
perfm$reg_grdsize <- c(lapply(perfm$csv_name[1:nrow(perfm)], function(f) strsplit(f, '_')[[1]][2]) %>% unlist() %>% as.numeric())
perfm$kernel <- c(lapply(perfm$csv_name[1:nrow(perfm)], function(f) strsplit(f, '_')[[1]][3]) %>% unlist() %>% as.character())
perfm$nfold <- lapply(perfm$csv_name[1:nrow(perfm)], function(f) strsplit(f, '_')[[1]][6]) %>% unlist() %>% as.character()
# ggplot(perfm)+
#    geom_line(aes(x=reg_grdsize, y=rsq, col=df_type))+
#    geom_point(aes(x=reg_grdsize, y=rsq, col=df_type))+
#    labs(title=paste0(unique(perfm$year), " (", unique(perfm$kernel), ")"),
#         x='grid cell size of regression coefficients (km)',
#         y='R squared',
#         col='data type')
ggplot(perfm)+
   geom_boxplot(aes(x=reg_grdsize, y=rsq, fill=df_type, group=reg_grdsize))+
   facet_grid(df_type~.)+
   labs(title=paste0(unique(perfm$year), " (", unique(perfm$kernel), ")"),
        x='grid cell size of regression coefficients (km)',
        y='R squared',
        col='data type')+
   theme(axis.title = element_text(size = 18),
          axis.text = element_text(size = 16),
          legend.title = element_text(size = 16),
          legend.text = element_text(size = 16))
```

